---
- hosts: apache
  #sudo: yes
  become: true
  become_method: sudo
  become_user: root
  #become: true
  vars:
    created_username: msis-cdc
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
