---
# Update the apt cache
- name: Update apt cache
  apt:
    update_cache: yes

# Install necessary packages
- name: Install Apache and PHP packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apache2
    - php
    - php-mysql
    - libapache2-mod-php
    - wget
    - tar

# Ensure Apache is enabled and started
- name: Ensure Apache is enabled and started
  service:
    name: apache2
    state: started
    enabled: yes

# Download the tarball containing the application code
- name: Download application code tarball
  get_url:
    url: "{{ app_tarball_url }}"
    dest: "{{ app_tarball_dest }}"

# Extract the tarball to the target directory
- name: Extract application code
  unarchive:
    src: "{{ app_tarball_dest }}"
    dest: "{{ app_extract_dest }}"
    remote_src: yes

# Copy getAppParameters.php template
# Copy getAppParameters.php template
- name: Copy getAppParameters.php template
  template:
    src: getAppParameters.php.j2
    dest: /var/www/html/mompopcafe/getAppParameters.php
# Update Apache configuration to point to the application directory
- name: Update Apache configuration
  template:
    src: "{{ apache_config_template }}"
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Reload Apache

